### ISSUE TITLE
interface.json not found after doing reset

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#137]
FileNotFoundError: [Errno 2] No such file or directory: '/state/interface.json'

**Comment by nicklambourne** [comment]
Is this still an issue @benfoley ?

**Comment by benfoley** [comment]
Yeah! Man this is annoying. Makes me want to remove the reset button 😆

**Comment by benfoley** [comment]
I'll look into it more soon

**Comment by benfoley** [comment]
Should be resolved by the update to resetting in #276
