### ISSUE TITLE
Elan file format is invalid

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#218]
The format of the downloaded ELAN file is invalid.

**Comment by nicklambourne** [comment]
That's new.

**Comment by benfoley** [comment]
ELAN now resolves files to a schema. This can be checked by using ELAN's `File > Validate EAF File` menu. 

Checking the generated file shows an invalid byte error, a tier type error and tier annotation errors. 

1) I'll look into the byte error soon.
2) The linguistic type error should be fixable by declaring one when the file is created rather than leaving it null.
3) Fixing 2 should resolve the third error.

[](url)
<img width="1106" alt="Screen Shot 2021-06-02 at 9 19 33 pm" src="https://user-images.githubusercontent.com/5652120/120727158-2cb95900-c51d-11eb-9e61-5944bf159fbf.png">

**Comment by benfoley** [comment]
Seems ok now
