### ISSUE TITLE
consolidate kaldi-helpers/elpis/docker 

### ISSUE THREAD

**Issue by benfoley** [CoEDL/elpis#35]
bring KH into the elpis repository, 
rename docker image

**Comment by fauxneticien** [comment]
- [ ] bring KH into the elpis repository,
- [x] rename docker image

https://cloud.docker.com/u/coedl/repository/docker/coedl/elpis

**Comment by benfoley** [comment]
- [x] Repositories have been rearranged
- [x] KH has been archived
- [x] Docker renamed
