### ISSUE TITLE
Seems to be bug.. Elpis is not built

### ISSUE THREAD

**Issue by dLeos** [CoEDL/elpis#66]
## Description

Cloned the repository and run "docker build".
Image building crashed at step 39.
Possibly due to npm packages being updated

## Environment

OS: Ubuntu 18.04 LTS
Docker version 19.03.2

## Expected Behavior

Image will be built

## Actual Behavior

    Step 39/46 : RUN npm install &&     npm run build

    ...
    > elpis-gui@0.1.0 build /elpis/elpis-gui
    > react-scripts build

    Creating an optimized production build...
    Failed to compile.
    
    ./src/redux/reducers/pronDictReducer.js
    Attempted import error: 'PRON_DICT_SAVE_LEXICON' is not exported from '../actionTypes/pronDictActionTypes' (imported as 'actionTypes').
    
    
    npm ERR! Linux 4.15.0-64-generic
    npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "build"
    npm ERR! node v8.10.0
    npm ERR! npm  v3.5.2
    npm ERR! code ELIFECYCLE
    npm ERR! elpis-gui@0.1.0 build: `react-scripts build`
    npm ERR! Exit status 1
    npm ERR! 
    npm ERR! Failed at the elpis-gui@0.1.0 build script 'react-scripts build'.
    npm ERR! Make sure you have the latest version of node.js and npm installed.
    npm ERR! If you do, this is most likely a problem with the elpis-gui package,
    npm ERR! not with npm itself.
    npm ERR! Tell the author that this fails on your system:
    npm ERR!     react-scripts build
    npm ERR! You can get information on how to open an issue for this project with:
    npm ERR!     npm bugs elpis-gui
    npm ERR! Or if that isn't available, you can get their info via:
    npm ERR!     npm owner ls elpis-gui
    npm ERR! There is likely additional logging output above.
    
    npm ERR! Please include the following file with any support request:
    npm ERR!     /elpis/elpis-gui/npm-debug.log

**Comment by benfoley** [comment]
Thanks for reporting, I'll check this out.

**Comment by benfoley** [comment]
Looks like one of the reducers was looking for an exported constant, that was not correctly named. Fixed in 494a8a

**Comment by benfoley** [comment]
Looks like there are a couple of other bugs which may prevent it running .. will aim to update in the next few days.

**Comment by benfoley** [comment]
Looks like the recent updates are working now, `docker build .` completes OK.
